"""empty message

Revision ID: 27a5b80dc62d
Revises: 06d72c03b23a
Create Date: 2022-05-22 21:38:08.723971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a5b80dc62d'
down_revision = '06d72c03b23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('classification', sa.String(length=120), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('average_height', sa.Integer(), nullable=True),
    sa.Column('skin_color', sa.String(length=120), nullable=True),
    sa.Column('hair_color', sa.String(length=120), nullable=True),
    sa.Column('eye_color', sa.String(length=120), nullable=True),
    sa.Column('average_lifespan', sa.Integer(), nullable=True),
    sa.Column('homeworld', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species')
    # ### end Alembic commands ###
