"""empty message

Revision ID: 8254052928f9
Revises: f6c753a138bf
Create Date: 2022-05-20 15:01:32.385440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8254052928f9'
down_revision = 'f6c753a138bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
